name: Build and deploy ASP.Net Core app to Azure Web App - bendapp24

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET Core SDK
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      # Restore dependencies
      - name: Restore dependencies
        run: |
          cd Eduhub/Eduhub/dotnetapp
          dotnet restore

      # Build with dotnet
      - name: Build with dotnet
        run: |
          cd Eduhub/Eduhub/dotnetapp
          dotnet build --configuration Release

      # Publish artifact
      - name: Publish artifact
        run: |
          cd Eduhub/dotnetapp
          dotnet publish --configuration Release --output ../myapp

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-app
          path: Eduhub/Eduhub/myapp

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: dotnet-app

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'eduhubapp24'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: Eduhub/Eduhub/myapp

   
