name: Deploy .NET Web API to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'  # Replace with your target .NET version

      - name: Change directory to project folder
        working-directory: Eduhub/Eduhub/dotnetapp  # Adjust to the path where your .csproj file is located
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Publish
        working-directory: Eduhub/Eduhub/dotnetapp  # Same directory as above
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'staging'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/publish
