name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Build and Deploy React App
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies for React app
      working-directory: Eduhub/Eduhub/reactapp
      run: npm install

    - name: Build React app
      working-directory: Eduhub/Eduhub/reactapp
      run: CI=false npm run build

    - name: Deploy React app to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'eduhubapp24'
        slot-name: 'staging'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: Eduhub/Eduhub/reactapp/build

    # Build and Deploy .NET App
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore .NET dependencies
      working-directory: Eduhub/Eduhub/dotnetapp
      run: dotnet restore

    - name: Build .NET app
      working-directory: Eduhub/Eduhub/dotnetapp
      run: dotnet build --configuration Release --no-restore

    - name: Publish .NET app
      working-directory: Eduhub/Eduhub/dotnetapp
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish --no-restore

    - name: Deploy .NET app to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'eduhubapp24'
        slot-name: 'staging'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/publish
